
# This Playbook can be used in conjunction with Tower and Tower's Survey Features of by adding extra_vars
# Needs venv_dir and ansible_re_version as 2 extra vars is using ansible-Playbook to executable

- hosts: all
  vars:
   venv_path:  "/var/lib/awx/venv"
  tasks:
   - name: Intialize the Virtual environments
     command: virtualenv "{{venv_path}}/{{venv_dir}}"
     args:
      creates: "{{venv_path}}/{{venv_dir}}"
   - name: Install Tower Prereqs in the VirtualEnv
     command:  "{{venv_path}}/{{venv_dir}}/bin/pip install python-memcached psutil"
   - name: Install the Version of Ansible needed in the Virtual Environment
     command:  "{{venv_path}}/{{venv_dir}}/bin/pip install -U 'ansible == {{ansible_re_version}}'"
