---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
     - name: Touch a file
       file: /tmp/touch
       state: touch
    - name: check state of system
       cmd: uname -a 
