# Create a Test User Using Ansible
- hosts: all
  gather_facts: no
  connection: ssh
  become_user: root
  become_method: sudo
  become: yes
  tasks:
   - name: Add group "developers" to remote server
     #become_method: sudo
     group:
       name: "{{group_name}}"
       state: present
   - name: Add user "farshad" to remote server
    # remote_user: ansible
    # become: yes
    # become_method: sudo
     user:
       name: "{{user_name}}"
       comment: "Privileged User"
       group: "{{group_name}}"
       append: yes
       shell: /bin/bash
       state: present
   - name: Set authorized key for user farshad copying it from current user
     authorized_key:
       user: "{user_name}"
       state: present
       key: "{{ lookup('file','/home/farshad/keys/id_rsa.pub') }}"
